name: algo-go
on:
  push:
    branches:
      - main
    paths:
    - .github/workflows/algo-go.yml
    - packages/algo-go/**
    - '!**/*.md'
  pull_request:
    paths:
    - .github/workflows/algo-go.yml
    - packages/algo-go/**
    - '!**/*.md'
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - uses: actions/checkout@v2
    # - name: Install Go dependencies
    #   run: make -C packages/algo-go/ install
    # - name: Build Go code
    #   run: make -C packages/algo-go/ build
    - name: Test Go code
      run: make -C packages/algo-go/ test
