name: algo-cpp

on:
  push:
    branches:
      - main
    paths:
    - .github/workflows/algo-cpp.yml
    - packages/algo-cpp/**
    - '!**/*.md'
  pull_request:
    paths:
    - .github/workflows/algo-cpp.yml
    - packages/algo-cpp/**
    - '!**/*.md'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -S $GITHUB_WORKSPACE/packages/algo-cpp -B ${{runner.workspace}}/packages/algo-cpp/build

    - name: Build
      working-directory: ${{runner.workspace}}/packages/algo-cpp/build
      run: cmake --build .

    - name: Test
      working-directory: ${{runner.workspace}}/packages/algo-cpp/build
      run: ctest -V
